# Generated by Django 5.2.6 on 2026-02-05 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('breedid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('breedname', models.CharField(max_length=100)),
                ('eggtype', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'breed',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('batchid', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('batchname', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('initial_male', models.IntegerField(blank=True, null=True)),
                ('initial_female', models.IntegerField(blank=True, null=True)),
                ('current_male', models.IntegerField(blank=True, null=True)),
                ('current_female', models.IntegerField(blank=True, null=True)),
                ('initialcount', models.IntegerField(editable=False)),
                ('currentcount', models.IntegerField(editable=False)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Terminated', 'Terminated'), ('Archived', 'Archived')], default='Active', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('breed', models.ForeignKey(db_column='breedid', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='batches.breed')),
            ],
            options={
                'db_table': 'batch',
            },
        ),
        migrations.CreateModel(
            name='DailyOperations',
            fields=[
                ('operationid', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('feedusage', models.FloatField(blank=True, null=True)),
                ('water_used', models.FloatField(blank=True, null=True)),
                ('eggcount', models.IntegerField(blank=True, null=True)),
                ('avgeggweight', models.FloatField(blank=True, null=True)),
                ('male_mortality', models.IntegerField(blank=True, null=True)),
                ('female_mortality', models.IntegerField(blank=True, null=True)),
                ('mortalitycount', models.IntegerField(editable=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(db_column='batchid', on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('stock', models.ForeignKey(blank=True, db_column='stockid', null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.feedstock')),
            ],
            options={
                'db_table': 'dailyoperations',
                'ordering': ['date'],
            },
        ),
    ]
