# Generated by Django 5.2.6 on 2026-02-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedStock',
            fields=[
                ('stockid', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('feedtype', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('lastupdated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Low Stock', 'Low Stock'), ('Out of Stock', 'Out of Stock')], default='Available', max_length=50)),
            ],
            options={
                'db_table': 'feedstock',
            },
        ),
    ]
