# Generated by Django 5.2.6 on 2026-04-02 02:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('nic', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('createat', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': '"User"',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notificationid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.CharField(blank=True, choices=[('INFO', 'Info'), ('ALERT', 'Alert'), ('WARNING', 'Warning')], default='INFO', max_length=20, null=True)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('isread', models.BooleanField(default=False)),
                ('referenceid', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleid', models.CharField(choices=[('A001', 'Admin'), ('A002', 'Owner'), ('A003', 'Manager'), ('B001', 'Buyer')], max_length=50, primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('settingsid', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('updateat', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
