# Generated by Django 5.2.8 on 2025-11-23 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userid', models.UUIDField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.TextField()),
                ('createat', models.DateTimeField()),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': '"User"',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rolename', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('notificationid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.CharField(blank=True, choices=[('INFO', 'Info'), ('ALERT', 'Alert'), ('WARNING', 'Warning')], max_length=20, null=True)),
                ('createat', models.DateTimeField()),
                ('isread', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, db_column='roleid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('settingsid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('parametername', models.CharField(blank=True, max_length=100, null=True)),
                ('parametervalue', models.CharField(blank=True, max_length=100, null=True)),
                ('updateat', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
