# Generated by Django 5.2.6 on 2026-04-02 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('buyerid', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('userid', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'buyer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ordereddate', models.DateField(blank=True, null=True)),
                ('requesteddate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('completeddate', models.DateField(blank=True, null=True)),
                ('breedid', models.ForeignKey(blank=True, db_column='breedid', null=True, on_delete=django.db.models.deletion.CASCADE, to='batches.breed')),
                ('buyerid', models.ForeignKey(db_column='buyerid', on_delete=django.db.models.deletion.CASCADE, to='orders.buyer')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['orderid'],
            },
        ),
        migrations.CreateModel(
            name='OrderBatch',
            fields=[
                ('batch_order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('batchid', models.ForeignKey(db_column='batchid', on_delete=django.db.models.deletion.CASCADE, related_name='batch_orders', to='batches.batch')),
                ('orderid', models.ForeignKey(db_column='orderid', on_delete=django.db.models.deletion.CASCADE, related_name='order_batches', to='orders.order')),
            ],
            options={
                'db_table': 'order_batch',
                'unique_together': {('orderid', 'batchid')},
            },
        ),
    ]
