# Generated by Django 5.2.6 on 2026-02-05 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('orders', '0001_initial'),
        ('predictions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportid', models.CharField(db_column='reportid', max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('generateddate', models.DateField(auto_now_add=True, db_column='generateddate')),
                ('filepath', models.TextField(blank=True, db_column='filepath', null=True)),
                ('batchid', models.ForeignKey(db_column='batchid', on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('generatedby', models.ForeignKey(blank=True, db_column='generatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('recordsid', models.CharField(db_column='recordsid', max_length=50, primary_key=True, serialize=False)),
                ('entrytype', models.CharField(blank=True, db_column='entrytype', max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
                ('hashvalue', models.TextField(db_column='hashvalue')),
                ('previoushash', models.TextField(blank=True, db_column='previoushash', null=True)),
                ('batchid', models.ForeignKey(blank=True, db_column='batchid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='batches.batch')),
                ('operationsid', models.ForeignKey(blank=True, db_column='operationsid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='batches.dailyoperations')),
                ('orderid', models.ForeignKey(blank=True, db_column='orderid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('predictionsid', models.ForeignKey(blank=True, db_column='predictionsid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictions.prediction')),
                ('reportsid', models.ForeignKey(blank=True, db_column='reportsid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report')),
            ],
            options={
                'db_table': 'records',
            },
        ),
    ]
