# Generated by Django 5.2.6 on 2026-04-02 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('recordsid', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('hashvalue', models.TextField()),
                ('previoushash', models.TextField(blank=True, null=True)),
                ('batchid', models.ForeignKey(db_column='batchid', on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('operationid', models.ForeignKey(db_column='operationid', on_delete=django.db.models.deletion.CASCADE, to='batches.dailyoperations')),
            ],
            options={
                'db_table': 'records',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('reportid', models.CharField(blank=True, db_column='reportid', max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('generateddate', models.DateTimeField(auto_now_add=True, db_column='generateddate')),
                ('filepath', models.TextField(blank=True, db_column='filepath', null=True)),
                ('batchid', models.ForeignKey(blank=True, db_column='batchid', null=True, on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('generatedby', models.ForeignKey(blank=True, db_column='generatedby', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-generateddate'],
            },
        ),
    ]
