# Generated by Django 5.2.6 on 2026-02-05 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batches', '0001_initial'),
        ('feed', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('managerid', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('userid', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('ownerid', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('farmname', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('userid', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'owner',
            },
        ),
        migrations.CreateModel(
            name='OwnerManagerBatch',
            fields=[
                ('batch_relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('batchid', models.ForeignKey(db_column='batchid', on_delete=django.db.models.deletion.CASCADE, to='batches.batch')),
                ('managerid', models.ForeignKey(db_column='managerid', on_delete=django.db.models.deletion.CASCADE, to='owners.manager')),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.CASCADE, to='owners.owner')),
            ],
            options={
                'db_table': 'owner_manager_batch',
                'unique_together': {('ownerid', 'managerid', 'batchid')},
            },
        ),
        migrations.CreateModel(
            name='OwnerManagerFeedstock',
            fields=[
                ('feed_relation_id', models.AutoField(primary_key=True, serialize=False)),
                ('managerid', models.ForeignKey(db_column='managerid', on_delete=django.db.models.deletion.CASCADE, to='owners.manager')),
                ('ownerid', models.ForeignKey(db_column='ownerid', on_delete=django.db.models.deletion.CASCADE, to='owners.owner')),
                ('stockid', models.ForeignKey(db_column='stockid', on_delete=django.db.models.deletion.CASCADE, to='feed.feedstock')),
            ],
            options={
                'db_table': 'owner_manager_feedstock',
                'unique_together': {('ownerid', 'managerid', 'stockid')},
            },
        ),
    ]
