# Generated by Django 5.2.6 on 2026-04-28 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ownermanagerfeedstock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ownermanagerfeedstock',
            name='managerid',
        ),
        migrations.RemoveField(
            model_name='ownermanagerfeedstock',
            name='ownerid',
        ),
        migrations.RemoveField(
            model_name='ownermanagerfeedstock',
            name='stockid',
        ),
        migrations.DeleteModel(
            name='OwnerManagerBatch',
        ),
        migrations.DeleteModel(
            name='OwnerManagerFeedstock',
        ),
    ]
